version: '3'

services:
  php8:
      build:
          context: ./docker/php8
      hostname: php8
      ports:
        - "9000:9000"
      volumes:
        - ./:/var/www/html/
        - ./docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./docker/php8/php.ini:/usr/local/etc/php/php.ini
      environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
  php7:
    image: php:7.4-fpm
    build:
      context: ./docker/php7
    hostname: php7
    ports:
      - "9001:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7/php.ini:/usr/local/etc/php/php.ini

    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  nginx:
        image: nginx:1.13.8
        ports:
          - "80:80"
        volumes:
          - ./:/var/www/html/
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php8
          - php7
  mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ideaSoft
        ports:
            - 3306:3306
        depends_on:
          - php8
          - php7